### ISSUE TITLE
Automate command documentation update

### ISSUE THREAD

**Issue by jblazek** [updatecli/website#685]
## Description

The docs page: https://www.updatecli.io/docs/commands/updatecli_manifest_show/ references options `--local-autodiscovery   Local AutoDiscovery feature enabled`.

It seems like other docs pages also reference this flag, but it's not available.

In the version I'm using, that flag returns `ERROR: ✗ unknown flag: --local-autodiscovery`.

```
VERSION

Application:    0.45.2
Golang     :    1.20.1 linux/amd64
Build Time :    2023-03-01T19:50:31Z
```

### Steps to reproduce

run `updatecli manifest show --local-autodiscovery`

### Expected result

Command runs, the flags should match the documentation.

### Actual result

Error listed above.

**Comment by olblak** [comment]
Thank you for this reminder, indeed I forgot to update those file since september 2022 :( .

When running the command `updatecli docs -d ./content/en/docs/commands`, the newly generated files have the the "date" and "lastmod" modified which requires me to do more than just adding an Updatecli manifest to run the command.

The content of those file shouldn't change much in the coming month so I am going to rename your issue to "automate documentation update for updatecli cl" and one more time update the content manually 

```
-date: 2022-09-20T18:24:41+02:00
-lastmod: 2022-09-20T18:24:41+02:00
+date: 2023-03-04T08:15:30+01:00
+lastmod: 2023-03-04T08:15:30+01:00

```

**Comment by olblak** [comment]
I opened this PR to update the doc https://github.com/updatecli/website/pull/688

**Comment by jblazek** [comment]
looks like the changes are present, closing this issue.
